cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --time={resources.time}
    --job-name=smk-{rule}
    --output=logs/{rule}/{rule}.{jobid}.%j.out
    --partition={resources.partition}
default-resources:
  - time="01:00:00"
  - partition="short"
  - tmpdir="/tmp"
  - mem_mb=1024
jobs: 150
latency-wait: 30
local-cores: 1
restart-times: 0
max-jobs-per-second: 10
keep-going: False
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-status: status-scontrol.sh
cluster-cancel: scancel
max-status-checks-per-second: 10
